#TargetName : Dependencies
#<tab>Commands


Build : project_main.c menu.c  help.c file.c quizC.c quizCpp.c quizJava.c
	gcc project_main.c menu.c  help.c file.c quizC.c quizCpp.c quizJava.c -o quiz.out


INC : ./inc\menu.h
	gcc menu.h